#node-emulator1.toml
[server]
port = 5533

[node]
detect-drivers = false

[relay]
url = "http://192.168.1.4:4723"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
    '1', '{"platformName": "iOS",  "appium:udid": "308CAD56-EE4E-470B-AABF-6A8A60B787B4", "appium:automationName": "XCUITest"}'
]
